### ISSUE TITLE
Broken Image coming

### ISSUE THREAD

**Issue by Karan102pal** [qijungu/screenshare#2]
![image](https://user-images.githubusercontent.com/15064664/119987744-f9d60900-bfe2-11eb-8b9e-ea3c68c512a1.png)
Instead of Screen shots, broken images are appearing. Please help me if I'am doing something wrong.

**Comment by EpicCodeWizard** [comment]
Same for me. Please fix soon.

**Comment by qijungu** [comment]
Added a few fixes. Mostly due to package changes in python3 and pyscreenshot.

**Comment by EpicCodeWizard** [comment]
I found a solution before you did, I just never posted it here. Good coding! I was making an app, which when you run the python script on your device, the program outputs a link to a 24/7 stream of your screen.
