### ISSUE TITLE
Idea: Login at web browser

### ISSUE THREAD

**Issue by caoviedog** [qijungu/screenshare#3]
Hi!:

There is a chance to add some security to this?
Request an user and password at the moment you try to get the screen in the web browser?
Can be a us/pw configured in a text file, encrypted or not.
Thanks a lot!

Carlos

**Comment by qijungu** [comment]
Yes, great and feasible and useful idea! Will give an update in a few days.

**Comment by qijungu** [comment]
Add a password control to login. But, screens are not encrypted.

**Comment by arturohope** [comment]
Hi,

In addition to what carlos proposed, is there a chance to make the app run as https instead of http to add another security feature besides the password.

Greetings.
Arturo

**Comment by qijungu** [comment]
Good idea. There are a few ways. But, let me find an easy one.
